CREATE TABLE IF NOT EXISTS corpus_occurrences (
  occurrence_id INTEGER PRIMARY KEY,
  guid VARCHAR(255) UNIQUE,
  record_guid UUID,
  modified_on TIMESTAMP,
  imaged BOOLEAN NOT NULL DEFAULT false,
  information_withheld TEXT,
  basis_of_record VARCHAR(255),
  herbarium VARCHAR(255),
  collection VARCHAR(255),
  dataset VARCHAR(255),
  accession VARCHAR(255),
  catalog VARCHAR(255),
  barcode VARCHAR(255),
  other_numbers VARCHAR(255),
  family VARCHAR(255),
  taxon_name VARCHAR(255),
  accepted BOOLEAN NOT NULL DEFAULT false,
  scientific_name VARCHAR(255),
  notho_genus VARCHAR(255),
  genus VARCHAR(255),
  notho_species VARCHAR(255),
  specific_epithet VARCHAR(255),
  specific_authors VARCHAR(255),
  infraspecific_rank VARCHAR(255),
  notho_infraspecies VARCHAR(255),
  infraspecific_epithet VARCHAR(255),
  infraspecific_authors VARCHAR(255),
  hybrid_symbol VARCHAR(255),
  notho_genus_2 VARCHAR(255),
  genus_2 VARCHAR(255),
  notho_species_2 VARCHAR(255),
  specific_epithet_2 VARCHAR(255),
  specific_authors_2 VARCHAR(255),
  infraspecific_rank_2 VARCHAR(255),
  notho_infraspecies_2 VARCHAR(255),
  infraspecific_epithet_2 VARCHAR(255),
  infraspecific_authors_2 VARCHAR(255),
  cultivar VARCHAR(255),
  name_qualifier VARCHAR(255),
  qualifier_position VARCHAR(255),
  is_type BOOLEAN NOT NULL DEFAULT false,
  type_designation VARCHAR(255),
  site_number VARCHAR(255),
  collector VARCHAR(255),
  collector_number VARCHAR(255),
  other_collectors VARCHAR(255),
  day_collected INTEGER,
  month_collected INTEGER,
  year_collected INTEGER,
  verbatim_collection_date VARCHAR(255),
  day_of_year INTEGER,
  country VARCHAR(255),
  state_province VARCHAR(255),
  county VARCHAR(255),
  locality TEXT,
  site_description TEXT,
  verbatim_elevation VARCHAR(255),
  minimum_elevation_in_meters NUMERIC,
  maximum_elevation_in_meters NUMERIC,
  verbatim_depth VARCHAR(255),
  minimum_depth_in_meters NUMERIC,
  maximum_depth_in_meters NUMERIC,
  verbatim_coordinates VARCHAR(255),
  decimal_latitude DECIMAL,
  decimal_longitude DECIMAL,
  valid_lat_lng BOOLEAN DEFAULT false,
  geodetic_datum VARCHAR(255),
  coordinate_uncertainty_in_meters NUMERIC,
  georeferenced_by VARCHAR(255),
  georeference_sources VARCHAR(255),
  georeference_remarks TEXT,
  specimen_notes TEXT,
  phenology VARCHAR(255),
  cultivated BOOLEAN NOT NULL DEFAULT false,
  origin VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS corpus_annotations (
  occurrence_id INTEGER REFERENCES corpus_occurrences(occurrence_id),
  current_annotation BOOLEAN,
  sequence_number INTEGER,
  family VARCHAR(255),
  scientific_name VARCHAR(255),
  notho_genus VARCHAR(255),
  genus VARCHAR(255),
  notho_species VARCHAR(255),
  specific_epithet VARCHAR(255),
  specific_authors VARCHAR(255),
  infraspecific_rank VARCHAR(255),
  notho_infraspecies VARCHAR(255),
  infraspecific_epithet VARCHAR(255),
  infraspecific_authors VARCHAR(255),
  hybrid_symbol VARCHAR(255),
  notho_genus_2 VARCHAR(255),
  genus_2 VARCHAR(255),
  notho_species_2 VARCHAR(255),
  specific_epithet_2 VARCHAR(255),
  specific_authors_2 VARCHAR(255),
  infraspecific_rank_2 VARCHAR(255),
  notho_infraspecies_2 VARCHAR(255),
  infraspecific_epithet_2 VARCHAR(255),
  infraspecific_authors_2 VARCHAR(255),
  cultivar VARCHAR(255),
  name_qualifier VARCHAR(255),
  qualifier_position VARCHAR(255),
  nomenclatural_code VARCHAR(255),
  annotated_by VARCHAR(255),
  day_annotated INTEGER,
  month_annotated INTEGER,
  year_annotated INTEGER,
  annotation_references VARCHAR(255),
  annotation_remarks TEXT
);

CREATE TABLE IF NOT EXISTS corpus_types (
  occurrence_id INTEGER REFERENCES corpus_occurrences(occurrence_id),
  sequence_number INTEGER,
  family VARCHAR(255),
  scientific_name VARCHAR(255),
  notho_genus VARCHAR(255),
  genus VARCHAR(255),
  notho_species VARCHAR(255),
  specific_epithet VARCHAR(255),
  specific_authors VARCHAR(255),
  infraspecific_rank VARCHAR(255),
  notho_infraspecies VARCHAR(255),
  infraspecific_epithet VARCHAR(255),
  infraspecific_authors VARCHAR(255),
  cultivar VARCHAR(255),
  type_designation VARCHAR(255),
  holotype_location VARCHAR(255),
  year_published INTEGER,
  publication VARCHAR(512),
  notes TEXT
);

CREATE TABLE IF NOT EXISTS corpus_media (
  occurrence_id INTEGER REFERENCES corpus_occurrences(occurrence_id),
  modified_on TIMESTAMP,
  media_guid VARCHAR(255),
  file_name VARCHAR(124),
  file_format VARCHAR(124),
  viewer_format VARCHAR(124),
  thumbnail_url VARCHAR(255),
  file_url VARCHAR(255),
  viewer_url VARCHAR(255),
  date_created TIMESTAMP,
  created_by VARCHAR(255),
  publisher VARCHAR(255),
  license VARCHAR(512)
);